import { GameEngine, GameEngineCallbacks } from '../../components/GameContainer';

type Card={id:number;revealed:boolean;matched:boolean};
const SYMBOLS=['◆','★','●','▲','✦','✚','◇','⬢'];
export class MemoryDuelEngine implements GameEngine {
  canvas:HTMLCanvasElement;ctx:CanvasRenderingContext2D;callbacks:GameEngineCallbacks;w=0;h=0;frame=0;last=0;running=false;gameOver=false;score=0;elapsed=0;lock=false;first=-1;matches=0;cards:Card[]=[];lockUntil=0;
  constructor(c:HTMLCanvasElement,cb:GameEngineCallbacks){this.canvas=c;this.ctx=c.getContext('2d')!;this.callbacks=cb;this.resize();window.addEventListener('resize',this.resize);this.canvas.addEventListener('pointerdown',this.tap);this.reset();}
  resize=()=>{this.w=innerWidth;this.h=innerHeight;this.canvas.width=this.w;this.canvas.height=this.h;};
  reset=()=>{const ids=[...Array(8).keys(),...Array(8).keys()];ids.sort(()=>Math.random()-.5);this.cards=ids.map(id=>({id,revealed:false,matched:false}));this.score=0;this.elapsed=0;this.matches=0;this.first=-1;this.lock=false;this.lockUntil=0;this.gameOver=false;this.last=performance.now();};
  start=()=>{if(this.running||this.gameOver)return;this.running=true;this.last=performance.now();this.frame=requestAnimationFrame(this.loop);};
  stop=()=>{this.running=false;cancelAnimationFrame(this.frame);window.removeEventListener('resize',this.resize);this.canvas.removeEventListener('pointerdown',this.tap);};
  tap=(e:PointerEvent)=>{if(this.gameOver||this.lock)return;const card=this.cardAt(e.clientX,e.clientY);if(card<0)return;const c=this.cards[card];if(c.revealed||c.matched)return;c.revealed=true;if(this.first<0){this.first=card;this.callbacks.playTone(440,'sine',.05,.1);return;}const f=this.cards[this.first];if(f.id===c.id){f.matched=c.matched=true;this.matches++;this.score+=100;this.callbacks.onScoreUpdate(this.score);this.callbacks.playTone(700,'triangle',.09,.18,1000);this.first=-1;if(this.matches===8)this.win();}else{this.lock=true;this.lockUntil=performance.now()+550;}};
  cardAt=(x:number,y:number)=>{const size=Math.min(72,(this.w-70)/4),gap=10,total=size*4+gap*3,left=(this.w-total)/2,top=Math.max(120,(this.h-total)/2+25);const col=Math.floor((x-left)/(size+gap)),row=Math.floor((y-top)/(size+gap));if(col<0||col>3||row<0||row>3)return -1;const cx=left+col*(size+gap),cy=top+row*(size+gap);return x<=cx+size&&y<=cy+size?row*4+col:-1;};
  win=()=>{if(this.gameOver)return;this.gameOver=true;this.score+=Math.max(0,Math.round(1000-this.elapsed*20));this.callbacks.onScoreUpdate(this.score);this.callbacks.onGameOver(this.score);};
  update=(dt:number)=>{if(this.gameOver)return;this.elapsed+=dt;if(this.lock&&performance.now()>=this.lockUntil){if(this.first>=0)this.cards[this.first].revealed=false;const open=this.cards.find(c=>c.revealed&&!c.matched);if(open)open.revealed=false;this.first=-1;this.lock=false;}if(this.elapsed>90)this.win();};
  draw=()=>{const c=this.ctx;c.fillStyle='#000';c.fillRect(0,0,this.w,this.h);const size=Math.min(72,(this.w-70)/4),gap=10,total=size*4+gap*3,left=(this.w-total)/2,top=Math.max(120,(this.h-total)/2+25);c.textAlign='center';c.textBaseline='middle';for(let i=0;i<16;i++){const col=i%4,row=Math.floor(i/4),x=left+col*(size+gap),y=top+row*(size+gap),card=this.cards[i];c.fillStyle=card.revealed||card.matched?'#064e3b':'#111113';c.strokeStyle=card.matched?'#34d399':'#27272a';c.lineWidth=2;c.fillRect(x,y,size,size);c.strokeRect(x,y,size,size);if(card.revealed||card.matched){c.fillStyle='#6ee7b7';c.font=`700 ${Math.floor(size*.42)}px system-ui`;c.fillText(SYMBOLS[card.id],x+size/2,y+size/2);}else{c.fillStyle='#27272a';c.font=`700 ${Math.floor(size*.3)}px system-ui`;c.fillText('?',x+size/2,y+size/2);}}c.textBaseline='alphabetic';c.fillStyle='#71717a';c.font='600 12px system-ui';c.fillText(`TIME ${this.elapsed.toFixed(1)}s`,this.w/2,top-18);};
  loop=(t:number)=>{if(!this.running)return;const dt=Math.min(.05,(t-this.last)/1000);this.last=t;this.update(dt);if(!this.running)return;this.draw();this.frame=requestAnimationFrame(this.loop);};
}
